---
title: "Self fertilization"
output: html_document
date: "2025-04-20"
---

#Import data
```{r cars, include=FALSE}
fecondation<-read.csv("D1_Data_self fertilization.csv",header = T,sep = ";", dec=",")
```

#Packages
```{r include=FALSE}
vapply(c("stringr","mgcv", "RColorBrewer", "dplyr","ggplot2","tidyverse", "lme4","vegan","emmeans","explor","ade4","FactoMineR"), library, logical(1L),
       character.only = TRUE, logical.return = TRUE)
```

#Visualize data
```{r}
library(Hmisc)
head(fecondation)
describe(fecondation)
```


```{r}
library(labelled)
fecondation$fruit<-as.factor(fecondation$fruit)
```

#Subset for each Aristolochia species
```{r}
fecrot<-subset(fecondation,fecondation$species=="A.rotunda")
fecpis<-subset(fecondation,fecondation$species=="A.pistolochia")
fecclem<-subset(fecondation,fecondation$species=="A.clematitis")
```

#Number of individuals for each modality
```{r}
fecondation$species |> questionr::freq()

length(unique(fecondation$flower[fecondation$species=="A.rotunda" & fecondation$modality=="HP"]))
length(unique(fecondation$flower[fecondation$species=="A.pistolochia" & fecondation$modality=="HP"]))
length(unique(fecondation$flower[fecondation$species=="A.clematitis" & fecondation$modality=="HP"]))
```

*Comparison of the probability of fructification according to treatment and species*

#A.clematitis

```{r}
library(lme4)
library(blme)

lmfecclem<-glm(fecclem$fruit ~ modality, data = fecclem, family=binomial(link = "logit"))

summary(lmfecclem)

library(DHARMa)
plot(simulateResiduals(lmfecclem))

library(MuMIn) 
r.squaredGLMM(lmfecclem)

anova(lmfecclem)
```

```{r}
library(marginaleffects)
lmfecclem |> 
  predictions(variables = "modality", by = "modality", type = "response")
```

#A.rotunda

```{r}
library(lme4)
library(blme)

lmfecrot<-glm(fecrot$fruit ~ modality, data = fecrot, family=binomial)

summary(lmfecrot)

library(DHARMa)
plot(simulateResiduals(lmfecrot))

library(MuMIn) 
r.squaredGLMM(lmfecrot)

anova(lmfecrot)
```

```{r}
library(marginaleffects)
lmfecrot |> 
  predictions(variables = "modality", by = "modality", type = "response")
```


#A.pistolochia

```{r}
library(lme4)

lmfecpis<-glm(fecpis$fruit ~ modality, data = fecpis, family=binomial)

library(DHARMa)
testpis<-simulateResiduals(lmfecpis, n = 250, refit = FALSE,
integerResponse = NULL, plot = FALSE, seed = 123, method = c("PIT",
"traditional"), rotation = NULL)

anova(lmfecpis, test = "Chisq")

library(DHARMa)
plot(simulateResiduals(lmfecpis))

library(MuMIn) 
r.squaredGLMM(lmfecpis)
```

```{r}
library(marginaleffects)
lmfecpis |> 
  predictions(variables = "modality", by = "modality", type = "response")
```